server:
  port: 6679
  servlet:
    context-path: /job

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mnsx.top:3306/mnsx_job?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: xx1527030652